### ISSUE TITLE
Does not work out of the box

### ISSUE THREAD

**Issue by LaurentDaudelin** [DoubleSymmetry/cocoapods-patch#8]
Created a simple Xcode project. Added the QKMRZScanner pod. Made changes to one of the file in the pod. Ran **pod patch create QKMRZScannerView** and got an error with no explanation:

```
Pod::StandardError - Could not install 'QKMRZScannerView' pod. There is either no platform to build for, or no target to build.
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:530:in `create_pod_installer'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-patch-0.0.6/lib/cocoapods-patch/command/patch/create.rb:36:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-patch-0.0.6/lib/cocoapods-patch/command/patch/create.rb:28:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `<main>'

```
No idea why I got this error. The QKMRZScanner pod works fine in my project.

This is my podfile:
```
platform :ios, '13'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TestOriginalMRZScanner' do
    pod 'QKMRZScanner'
end

plugin 'cocoapods-patch'
```

**Comment by LaurentDaudelin** [comment]
So, I think I understand why the error above. You seem to need to specify for the diff the exact name of the pod? I tried that and instead got this:
```
lvcowdhs523956:TestOriginalMRZScanner ldaudel$ pod patch create QKMRZScanner
Analyzing dependencies
sh: /Users/ldaudel/Documents/GitHub/TestOriginalMRZScanner/patches/QKMRZScanner.diff: No such file or directory
Created patch /Users/ldaudel/Documents/GitHub/TestOriginalMRZScanner/patches/QKMRZScanner.diff
```
But it didn't create the **patches** directory and there was obviously no diff file either...

**Comment by dcvz** [comment]
Thanks for the report @LaurentDaudelin.

Are you working in a standard iOS project or are you working in a monorepo?

**Comment by dcvz** [comment]
@LaurentDaudelin this has now been fixed in v0.0.7 :)
Can you please give this another try?

I'll also make a note to give a clearer warning if you try to create a patch using the wrong Pod name :)

**Comment by LaurentDaudelin** [comment]
It still doesn't work. I'm working in a standard iOS project (from react-native). What is not clear is what should be the active directory when you run pod patch create. The main directory? The Pods directory? The specific pod directory where the modification occured? I just tried it from the main project directory (the one that contains the "Pods" directory):

```
litwkice172301:ios ldaudel$ pod patch create QKMRZScanner
Auto-linking React Native modules for target `ScanID`: RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, RNVectorIcons, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
sh: /Users/ldaudel/Documents/GitHub/Original_ReactNative_Scanner_Integration/ScanID-master/ios/patches/QKMRZScanner.diff: No such file or directory
Created patch /Users/ldaudel/Documents/GitHub/Original_ReactNative_Scanner_Integration/ScanID-master/ios/patches/QKMRZScanner.diff

```
The tool reports it created a diff file at **/Users/ldaudel/Documents/GitHub/Original_ReactNative_Scanner_Integration/ScanID-master/ios/patches/** but there is no **patches** directory under ios.

**Comment by LaurentDaudelin** [comment]
Seems to work now. Thanks for the update!

**Comment by dcvz** [comment]
Great to hear it! Thanks for the report @LaurentDaudelin :)
